### ISSUE TITLE
how to build this project

### ISSUE THREAD

**Issue by okou19900722** [reactiverse/es4x#112]
I want to run this project on my computer and make a contribution, but I don't know how to run it.

**Comment by pmlopes** [comment]
Hi,

Yes this needs to be improved. The build process is complicated.

1. `mvn clean install` from the root will build all the maven bits
2. if you don't have a npm proxy, install `npm install -g verdaccio` and follow the instructions to login
3. `cd generator`
4. this is where all generation happens `./generate.sh local` this will generate all packages and push to your local proxy (not npm central)
5. `cd pm`
6. this is the cli tool: `./publish.sh` (again it will go to your local proxy)

If you get an error because the size of the upload edit the config (`~/.config/verdaccio/config.yaml`)

```yaml
# max package size
max_body_size: 100mb
```

Now you should have all your packages in your proxy and you can use them from NPM.

Perhaps this should be better documented as a proper doc, are you willing to do a PR? with this notes and verifying that they are ok?

**Comment by pmlopes** [comment]
Also `verdaccio` could be configured to ignore `@vertx` packages from upstream so you only see the ones you build: see: https://verdaccio.org/docs/en/best

Or we could document how to use tags to allow temporary overrides (like maven snapshots) which i'm not 100% sure how to achieve yet...

**Comment by okou19900722** [comment]
thanks, It's really complicated. 

you may had saw my pr. It's work with `vertx-codegen` in maven，so I add `parent` and `generator` to the pom of `es4x-parent`. It's worked.

thanks again

**Comment by pmlopes** [comment]
I don't have those in the parent pom because when releasing I don't want those artifacts to go to maven central. I believe there should be a pom in the generator that replaces the script

**Comment by pmlopes** [comment]
@okou19900722 I've added a few more docs here:

https://github.com/reactiverse/es4x/blob/develop/docs/contributing.md#building-the-world

I'll soon publish this into the main site docs

**Comment by okou19900722** [comment]
thanks

**Comment by frank-dspeed** [comment]
https://github.com/reactiverse/es4x/blob/develop/docs/get-started/hello-world.md is now the correct link
