### ISSUE TITLE
Question: How to transpile classes in project?

### ISSUE THREAD

**Issue by rquast** [reactiverse/es4x#18]
I've managed to get the Java imports working great, but now I'm trying to import a class and it won't work. It appears it needs to be transpiled.

What doesn't work:

In my index.js I have ```import {Licensee} from './src/routes/licensee';``` and licensee.js is just:

```
export class Licensee {
    test() {
        return 'IT WORKS';
    }
}
```

What does work:
index.js:
```
const Licensee = require('./src/routes/licensee');
```
licensee.js:
```
exports.test = function() {
        return 'IT WORKS';
};
```

Any tips on how to get it to transpile with the class? Very much appreciated! :)

**Comment by rquast** [comment]
Oh I think you might be just transpiling a few things like import in your own code. https://github.com/reactiverse/es4x/blob/1dd29491cb2e9783a2a6a3d271b9891d9aac297d/src/main/java/io/reactiverse/es4x/ESModuleAdapter.java#L73

I thought it was running through typescript or something. Makes sense now.

So it's up to me to implement my own typescript transpilation then I guess? :)

**Comment by pmlopes** [comment]
@rquast this project doesn't do any special transpilation, you can see what ES6 level is supported by your runtime in the kangax table:

* Running on JDK 1.8 https://kangax.github.io/compat-table/es6/#nashorn1_8
* Running on JDK >=9 https://kangax.github.io/compat-table/es6/#nashorn10

The only "trick" this project does is what you've just spotted, allow ES6 import syntax to be converted to `commonjs` require statements, mostly because IDEs such as vscode when using this format will pull the right type definition files giving you type hinting and proper code completion.

If you need more advanced features then you should rely on a ES6 transpiler such as `babel`, `buble`, `traceur`, etc... but this is not included in this project.

The reason is that the same runtime will run on `GraalVM` which is already ES6 ready (GraalVM support is still very experimental and has not been production tested, so currently it is just a development feature).

**Comment by rquast** [comment]
Awesome! Thanks for the quick and detailed response Paulo!
