### ISSUE TITLE
Misdocumented getting a verticle configuration

### ISSUE THREAD

**Issue by Asfolny** [reactiverse/es4x#187]
[Context::config()](https://reactiverse.io/es4x/@vertx/core/classes/context.html#config) is typed to be a JS object of {[key: string] : any} | null.
It's not, specifically it's a [vert.x/JsonObject](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/json/JsonObject.java).
Implicating that doing config.key will return undefined.

Vert.x is nice enough to provide a getValue, as well as an overload to get a default value should the key not exist though.

Worthy note: this [Vertx blog post](https://vertx.io/blog/vert-x-application-configuration/) describes just calling "config()", while calling it as a function creates a java exception, "config" is actually a global...
But it's a java object with a string format of {key=value}, so it's essentially useless.

I did try to look into changing this myself, so I could just submit a PR, but honestly I can't make head nor tail out of how the typing generator works, or how to help it.

**Comment by pmlopes** [comment]
You're correct the way verticles work on es4x are slightly different from Java. In Java there's the need to implement an interface in es4x the main script is the "body" of the verticle so the methods `config()` does not exist, but there are a few globals: `config`, `vertx`, `process`, `console`, etc...

You also noticed a bug in the generated type definitions, the generated code "assumes" that the Java type `JsonObject` can be used like a JS `Object` which sadly isn't true see:

* https://github.com/graalvm/graaljs/issues/203
* https://github.com/graalvm/graaljs/issues/144

Which means that returned `JsonObject`s need to follow the Java API not `{[key: string] : any}`

With vert.x 4 there's a chance that `JsonObject` will implement the `Map` interface which would make things simpler (is the first graal issue is fixed) but the best solution would be the fix of the second issue.

In the meantime if there is a simple type definition of the classes:

* `io.vertx.core.json.JsonObject`
* `io.vertx.core.json.JsonArray`

A fix would be to update the code generator to issue `JsonObject` instead of `{[key: string] : any}`

If you want to contribute I can assist you. The steps are:

1. create the type definitions
2. Update the generator to use the new types here https://github.com/reactiverse/es4x/blob/develop/codegen/src/main/java/io/reactiverse/es4x/codegen/generator/Util.java#L155 and https://github.com/reactiverse/es4x/blob/develop/codegen/src/main/java/io/reactiverse/es4x/codegen/generator/Util.java#L157
3. A special note should be done as this is only needed for returned types, in arguments these types are converted by graalvm

**Comment by Asfolny** [comment]
Been a few days, did try 0.9.1;
Since it fixes this issue, and probably any related to `JsonObject` (even if only with a experimental flag) this can be closed.

Other than that, I don't have any real input here, I'm not using Java arrays enough to say anything on those, but at least people can know objects work just fine now :D
