### ISSUE TITLE
If es4x is so fast why it's not so popular?

### ISSUE THREAD

**Issue by ConsMe** [reactiverse/es4x#277]
Sorry for my question here, I can remove it if you want. 
But If es4x is so fast why it's not so popular? What is its bottlenecks/problems/issues? I can't understand. What should I know if I'm going to use es4x?
Thank you.

**Comment by pmlopes** [comment]
There are a few factors to consider, es4x is a small project, started as an experiment with the sole goal of having a high performance server runtime using vert.x as underlying technology and javascript as programming model.

As you know, javascript has a huge community around nodejs and npm packages. You will find virtually any answer you search on stackoverflow, npm packages or blogs so, for a new comer it makes sense to stay on that world.

Since this started as a research project and is not backed by any commercial company, there is no guaranteed job security which makes it also less attractive than node for example where there are many job posts in any place of the planet.

Now, we know that all projects start from 0, what es4x is offering is quite interesting to users who have a clear need for performance (yet staying on the javascript language). Given it's "niche" and because it's not a generalist platform adoption will be slow.

Also going back to the module experience, currently npm has modules for virtually anything, while es4x will require modules that are compatible with either vert.x or do not relly on node internal modules. This means although for many users there is a reasonable set of modules that cover most of the needs. For example, web routing, security, database access, etc... there will always be a lack of modules.

Finally, and probably the hardest blocker to adoption is scepticism. All the years of unfounded information that the JVM is slow and V8 is fast, are deeply infiltrated on the developer mind of us that will not believe on the results.

I believe that more benchmarks, real world examples from users other than the project would give an encouragement feeling to new users to look and explorer the limits of this project.

**Comment by McSneaky** [comment]
I'm using it one small personal project and really interested in es4x (that's why I have all notifications on :smile: )
But coming from C -> PHP -> JS background figuring out how to make everything work correctly was quite a pain. Installed all those JVMs and GraalVMs etc. :| Not sure if I even did get it in the end so I just went with preconfigured Dockerfile

_Did it al several months ago, something might have been changed by now_

**Comment by ConsMe** [comment]
Thank you @pmlopes. 
I think I should try it.

**Comment by pmlopes** [comment]
@McSneaky I saw that there's a official graalvm vscode plugin that install it. I'll give it a shot, if it works as advertised, then it will simplify the dev setup (yet it will be biased to a default environment on vscode).

**Comment by pmlopes** [comment]
For reference here's the plugin: https://marketplace.visualstudio.com/items?itemName=oracle-labs-graalvm.graalvm

**Comment by ConsMe** [comment]
Please help me.
I try to import Router from @vertx/web and get error:
Failed in deploying verticle caused by TypeError: Access to host class io.vertx.ext.web.handler.AuthHandler is not allowed or does not exist.

What could be the reason for this error?

**Comment by pmlopes** [comment]
Can you just remove your local `node_modules` and re run npm install?  It looks like the jvm dependencies are missing

**Comment by ConsMe** [comment]
It helped! Thank you!

**Comment by McSneaky** [comment]
I just found that I have made severe mistake when benchmarking my small projects in Node vs ES4X.

So far I got quite small performance difference when doing benchmark with Apache ab (used it years ago to test php 4 and 5 so been using it out of old hobbit)

Didn't bother to write too much new stuff on ES4X since performance difference was only about 20% or so..

Neither did I notice any difference between running ES4X on one verticle or on 16 verticles, but now found that I've been hitting the limit of ab :sweat_smile: 

Replaced Apache ab with wrk and doing same benchmarks again there is about 5-6 times performance difference Node and ES4X! 

Time to write more stuff on ES4X! :smile:

**Comment by stephenh** [comment]
@pmlopes kind of a lazy ask sneaking this into a github issue vs a DM/something, but iirc ~awhile ago/initially es4x was in like top-10/top-20 on the techempower benchmarks and is now like ~70th. Do you have a quick tldr of why it dropped ~50 slots?

Fwiw I still think this is an impressive project, and the techempower stuff is interesting but still "just a benchmarket"/so take it with a grain of salt.

But still just wondering if there was an initial benchmarking mistake (which is super easy to have happen/np) or maybe a change in es4x that was required for semantic correctness but slowed things down.

Thanks!

**Comment by pmlopes** [comment]
Hi @stephenh, looking at tha runs that will become round 19:

https://www.techempower.com/benchmarks/#section=test&runid=9a267248-17b0-4080-ac45-a50d25b4fc2a
https://www.techempower.com/benchmarks/#section=test&runid=600c3cb5-8e8c-4434-be90-9b2fcd6d4b06

You can see that es4x ranks in avg:

* json - 70th
* single query - 10th
* multiple queries - 11th
* fortunes - 38th
* updates - 6th
* plaintext - 73th

So let me quickly explain, the `json` and `plaintext` are outliers. These tests do not represent a real use case, they just test the network stack of the framework. Many people have noticed that they can get better results by disabling many of the things you usually do, like header parsing, validation. Some (and there's now a discussion on how to make this fair) have used less headers or shorter headers and url paths with a single character which would make the request and response payload even smaller, thus faster.

I've decided to avoid any benchmarking gaming, what you get is what you will use in production, so of course, as I'm not gaming, my results drop (and I'm fine with it as on the next round things will be a bit fairer but I don't expect to be on the top 10 for those tests anyway).

The remaining tests, which are more fair to everyone and resemble real use cases: `single query`, `multiple queries`, `fortunes` and `updates` I rank quite OK, for the data driven ones (like the use case of REST APIs) it ranks at 10th, 11th and 6th. Which is quite good for a javascript framework.

The `fortune` test is a mix of the data test + a template engine. Now Ive choosen a engine that is fast enough still portable. You will see that the engines used by the top results are using "smart" assembly instructions to do character encoding 8 or 16 bytes at a time using SIMD instructions. I decided to use exactly what you would on prod, not game the benchmark or use some complex non js setup so it ranks at 38th.

Now if you look at the `js` only results you can see that `es4x` is the clear winner still.

https://www.techempower.com/benchmarks/#section=test&runid=600c3cb5-8e8c-4434-be90-9b2fcd6d4b06&hw=ph&test=json&l=zik0sf-1r

* json - es4x 905494rps - 2nd - 563407rps
* single query - es4x 531805rps - 2nd 176174rps
* multiple queries - es4x 32210rps - 2nd - 14341rps
* fortunes - es4x 236801rps - 2nd - 130065rps
* updates - es4x 17151rps - 2nd 4970rps
* plaintext - es4x 2143745rps - 2nd - 886579rps

So in the end, it all sums to, I don't want to bother gaming the benchmark. I want to showcase code like you would write for production. Yet faster than any other JS framework and ranking on the top 20 for many tests.

I hope this makes it more clear and helps understanding the results.

**Comment by stephenh** [comment]
@pmlopes thanks, that is a great explanation! Totally agreed that playing the benchmark game is not worth your time (and that es4x still has amazing results regardless). Would love to see es4x drive some adoption of graal.js in production environments.
