### ISSUE TITLE
using es4x vs other frameworks on graalvm

### ISSUE THREAD

**Issue by tweenietomatoes** [reactiverse/es4x#352]
what's the difference between using es4x vs other frameworks on graalvm?
if it's running on graalvm isn't that fast enough? what's es4x bringing?

**Comment by pmlopes** [comment]
Hi, graalvm is just a runtime, like the jvm or v8. You can use it to write your applications but you will need to implement everything yourself.

Es4x is just exposing the vertx toolkit but not in java (it's original language) but JavaScript.  On top of this it implements a basic module loader in common js so you can use npm to build your app.

So basically it's just a facade to a well-known toolkit with extra tooling to make your dev experience easier.

**Comment by tweenietomatoes** [comment]
i know but im curious about it's performance vs other frameworks.

for example well known express js on graalvm node vs es4x.

**Comment by pmlopes** [comment]
es4x will still be faster than express on graalvm. The reason is that graalvm node is just node, replacing v8 with graaljs. Vertx and Netty have better performance than libuv. Plus the graal compiler has full application statistics on es4x so it can optimize the whole stack while node only optimizes the script code.
