### ISSUE TITLE
(BUG) adapt should adapt based on environment

### ISSUE THREAD

**Issue by frank-dspeed** [reactiverse/es4x#406]
The adapt on filesystemload should not adapt ESM code to Require inside esm +module
it should adapt CJS code to CJS Wrapper function 

adapt running inside ESM import and import() of CJS Files 
adapt running inside CJS import() of CJS Files
```js
function createCommonjsModule(fn, module) {
 return module = { exports: {} }, fn(module, module.exports), module.exports;
}

export default createCommonjsModule(function (module,exports) {
 // => Module Code CJS Here
 // .....
})()
``` 

@laiweiwei has done a good adapt version when running inside CJS when using require() with ESM

**Comment by pmlopes** [comment]
I think the whole adapt should be deprecated and eventually removed. The reason I've created the adapt initially was because `Visual Studio Code` module auto complete would always use the `ESM` import syntax. It seems now, that they changed the behavior to use `commonjs` require statements, voiding the need for this hack.

**Comment by frank-dspeed** [comment]
@pmlopes it should get optional load able for the filesystem to call a load and resolve hook that would be the best.

**Comment by frank-dspeed** [comment]
close in favor of: #410
