### ISSUE TITLE
es4x.d.ts will be removed when use npm install xxx --save

### ISSUE THREAD

**Issue by fantasy0v0** [reactiverse/es4x#436]
```bash
# (1) create
npm init @es4x project

# (2) install dependencies
npm install # OR yarn

# (3) install something
npm install --save luxon

# (4) node_modules/@types/es4x.d.ts will be removed
```

**Comment by pmlopes** [comment]
Indeed, it's tricky as this is the global definition for the runtime, not a package.

**Comment by pmlopes** [comment]
@fantasy0v0 I think I've a proper solution for this. I'll include the content of `@types/es4x.d.ts` into `@vertx/core/index.d.ts`.

All projects will have the vertx/core dependency, it's a required runtime one. By doing this and updating all templates to use:

```js
/// <reference types="@vertx/core" />
```

instead of

```js
/// <reference types="es4x" />
```

The global type definitions do not need to be re-installed on each npm install. Which means less code run during install or updates as the file does not need to be extracted from the package to the runtime project node modules.

I've been checking how it would work, and both `vscode` and `webstorm` seem to be happy with this change, which is interesting as it was something I wanted to fix for webstorm for a while.

**Comment by pmlopes** [comment]
We hope to release a new RC of vert.x this week. After that I'll try to make a `prerelease` also on `es4x`

**Comment by pmlopes** [comment]
Should be fixed on the RC1 release.
