### ISSUE TITLE
Multiple verticle instances generate bad context exceptions from graalvm when loading modules from common npm packages

### ISSUE THREAD

**Issue by chefhoobajoob** [reactiverse/es4x#579]
[See here](https://github.com/chefhoobajoob/es4x-multithreaded-access) for a reproducer using rxjs to illustrate. If two or more verticle instances are deployed that each use one or more large/modularized-enough npm packages in common, then the second verticle instance to attempt to load one of these packages' modules will result in a graalvm PolyglotException citing either a [multi-threaded access](https://github.com/oracle/graal/blob/3d94e74fdd6b1d51b1fb90db357403dd5bc87cca/truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/PolyglotContextImpl.java#L910) or [wrong context assertion](https://github.com/oracle/graal/blob/20431472b644bccecb0e01107dc2828893b1c3e7/truffle/src/com.oracle.truffle.host/src/com/oracle/truffle/host/HostContext.java#L316) error.

Reproducible on es4x 0.17.0, vertx 4.2.4

**Comment by pmlopes** [comment]
As @chefhoobajoob noted graalvm file system is expected to be set per graal context, while we share a global FS. This sharing may be the root cause of the wrong thread exception.

We should rewrite the filesystem implementation to use a correct vert.x context as this ensures that we also are on the right thread most of the times.
