### ISSUE TITLE
A way to customize the Dockerfile ?

### ISSUE THREAD

**Issue by sdnetwork** [reactiverse/es4x#85]
Hi,

i search a solution to customize the Dockerfile, for example add cluster parameter in the entrypoint, for now i change directly into the Dockerfile but i think we can do better like .pom.xml ?

Maybe we can do it but i don't find how.

**Comment by pmlopes** [comment]
Hi @sdnetwork the current goal is to drop the usage of maven under the hood. In order to still provide the same functionality an utility project `es4x-pm` is being developed which is basically the minimal runtime so you can use `shebang` scripts and a bunch of several lanchers that do several stuff:

* https://github.com/reactiverse/es4x/blob/develop/pm/src/main/java/io/reactiverse/es4x/commands/InitCommand.java - creates a barebones `package.json`
* https://github.com/reactiverse/es4x/blob/develop/pm/src/main/java/io/reactiverse/es4x/commands/InstallCommand.java - downloads all the java artifacts from maven
* https://github.com/reactiverse/es4x/blob/develop/pm/src/main/java/io/reactiverse/es4x/commands/VersionsCommand.java - prints all versions es4x, vertx and graal
* https://github.com/reactiverse/es4x/blob/develop/pm/src/main/java/io/reactiverse/es4x/commands/JLinkCommand.java - creates a small JDK11 runtime
* https://github.com/reactiverse/es4x/blob/develop/pm/src/main/java/io/reactiverse/es4x/commands/DockerfileCommand.java - Creates a `Dockerfile` for the current project

The goal is to avoid "magic". The docker command will create the barebones dockerfile and you can then hack it and build it the usual way, so customization can be stored in your git repository.

**Comment by sdnetwork** [comment]
Amazing that's all i need !

i play with the es4x-pm in develop branch and the mvnDependencies into the project package.json 
```
"mvnDependencies" : [
    "io.vertx:vertx-hazelcast:3.6.3"
]
```
and generate the Dockerfile with es4x dockerfile
